import { Brain, BarChart3, Clock, BookOpen, Trophy, Lightbulb } from "lucide-react";

const features = [
  {
    icon: Brain,
    title: "AI-Powered Questions",
    description: "Get intelligent, contextually relevant questions generated by advanced AI models.",
    color: "text-blue-600",
    bgColor: "bg-blue-500/10",
  },
  {
    icon: BarChart3,
    title: "Performance Analytics",
    description: "Track your scores and see detailed analytics of your learning progress.",
    color: "text-green-600",
    bgColor: "bg-green-500/10",
  },
  {
    icon: Clock,
    title: "Save Time",
    description: "Generate comprehensive quizzes in seconds instead of spending hours creating them.",
    color: "text-purple-600",
    bgColor: "bg-purple-500/10",
  },
  {
    icon: BookOpen,
    title: "Any Topic",
    description: "Create quizzes on virtually any subject from programming to history to science.",
    color: "text-orange-600",
    bgColor: "bg-orange-500/10",
  },
  {
    icon: Trophy,
    title: "Gamified Learning",
    description: "Make learning fun with scores, achievements, and progress tracking.",
    color: "text-yellow-600",
    bgColor: "bg-yellow-500/10",
  },
  {
    icon: Lightbulb,
    title: "Smart Explanations",
    description: "Get instant feedback and understand why answers are correct or incorrect.",
    color: "text-pink-600",
    bgColor: "bg-pink-500/10",
  },
];

export default function Features() {
  return (
    <section className="py-20 bg-muted/30">
      <div className="container mx-auto px-4">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Everything You Need to{" "}
            <span className="bg-gradient-to-r from-primary to-purple-600 bg-clip-text text-transparent">
              Master Any Topic
            </span>
          </h2>
          <p className="text-lg text-muted-foreground">
            Powerful features designed to make learning effective, engaging, and fun.
          </p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          {features.map((feature, idx) => (
            <div
              key={idx}
              className="group p-6 rounded-xl bg-card border border-border hover:border-primary/50 hover:shadow-lg transition-all duration-300"
            >
              <div className={`w-12 h-12 rounded-lg ${feature.bgColor} flex items-center justify-center mb-4 group-hover:scale-110 transition-transform`}>
                <feature.icon className={`w-6 h-6 ${feature.color}`} />
              </div>
              <h3 className="font-semibold text-xl mb-2">{feature.title}</h3>
              <p className="text-muted-foreground">{feature.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
